# Generated by Django 5.2.5 on 2025-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='id_especialidade',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_medico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
